builds:
  -
    env:
    - CGO_ENABLED=0
    goos:
    - linux
    - darwin
    goarch:
    - amd64
    - arm64
    - arm
    goarm:
    - 6
    - 7
archives:
  - format: zip
    format_overrides:
      - goos: linux
        format: tar.gz
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: howardZa
    name: fritz-tls
brews: []
